### ISSUE TITLE
Flovatar dust has wrong coingecko id

### ISSUE THREAD

**Issue by PeterBenc** [FlowFans/flow-token-list#67]
https://github.com/FlowFans/flow-token-list/blob/cecc35ad9ae0fd268fb0c431c3d9ab8a1b5653ca/src/tokens/flow-mainnet.tokenlist.json#L472

Current coingecko id (wrong)
`flovatar-dust-token`

https://api.coingecko.com/api/v3/simple/price?ids=flovatar-dust-token&vs_currencies=usd

Correct coingecko id (right)
`flovatar-dust`

https://api.coingecko.com/api/v3/simple/price?ids=flovatar-dust&vs_currencies=usd

**Comment by btspoony** [comment]
Fixed
